# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-03 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='buy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=2500)),
                ('lname', models.CharField(max_length=2500)),
                ('contact', models.CharField(max_length=2500)),
                ('location', models.CharField(max_length=2500)),
            ],
        ),
        migrations.CreateModel(
            name='workers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=2500)),
                ('lname', models.CharField(max_length=2500)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=10)),
                ('Id', models.CharField(blank=True, max_length=10)),
                ('location', models.CharField(max_length=2500)),
                ('profile', models.FileField(upload_to='images/%Y/%m/%d/')),
            ],
        ),
    ]
