# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-03 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanjye', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workers',
            name='profile',
            field=models.FileField(upload_to='images/'),
        ),
    ]
