# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-03 12:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nanjye', '0003_auto_20190403_0957'),
    ]

    operations = [
        migrations.CreateModel(
            name='buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=2500)),
                ('lname', models.CharField(max_length=2500)),
                ('contact', models.CharField(max_length=2500)),
                ('location', models.CharField(max_length=2500)),
                ('phone', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2500)),
                ('discription', models.CharField(max_length=2500)),
                ('price', models.CharField(max_length=2500)),
            ],
        ),
        migrations.DeleteModel(
            name='buy',
        ),
        migrations.RemoveField(
            model_name='workers',
            name='Id',
        ),
        migrations.RemoveField(
            model_name='workers',
            name='email',
        ),
        migrations.AddField(
            model_name='workers',
            name='NID_PASSPORT',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='workers',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
