# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-23 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanjye', '0005_auto_20190423_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='profile_product',
        ),
        migrations.AddField(
            model_name='image',
            name='profile_product1',
            field=models.FileField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='image',
            name='profile_product2',
            field=models.FileField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='image',
            name='profile_product3',
            field=models.FileField(null=True, upload_to='images/'),
        ),
    ]
