# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-24 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanjye', '0006_auto_20190423_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='welcomeimages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tittle', models.CharField(max_length=30)),
                ('publish_image', models.FileField(null=True, upload_to='images/')),
                ('small1_banar', models.FileField(null=True, upload_to='images/')),
                ('small2_banar', models.FileField(null=True, upload_to='images/')),
                ('small3_banar', models.FileField(null=True, upload_to='images/')),
                ('small4_banar', models.FileField(null=True, upload_to='images/')),
            ],
        ),
    ]
