# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-25 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanjye', '0007_welcomeimages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='welcomeimages',
            old_name='publish_image',
            new_name='publish_image_for_present',
        ),
        migrations.AddField(
            model_name='welcomeimages',
            name='small5_banar',
            field=models.FileField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='welcomeimages',
            name='small6_banar',
            field=models.FileField(null=True, upload_to='images/'),
        ),
    ]
